#!/bin/bash
preamb='
\relax
\documentclass[preview,fleqn]{standalone}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[english,russian]{babel}
\usepackage{xcolor}
\usepackage{nicefrac}
\let\lfrac\nicefrac
'
mathpkg='
\usepackage{amsmath,amssymb,amsfonts}
'
begin='
\begin{document}
'
inversebeg=

begmath='
\[\hspace{-3em}
'
formula=

endmath='
\]
'
inverseend=

end='
\end{document}
'
debug=0
preview=0
inverse=0
nomath=0
output=

disp_help() {
    echo "
    Usage: easyltx [flags...] '\sum_{i=1}^{\infty} a_i'
    Flags: 
        --debug,   -h --- print debug info
        --help,    -d --- display help
        --preview, -p --- preview generated image
        --inverse, -i --- inverse image colors
        --tmath  , -t --- for taxus: use tmath.sty
        --hook   , -k --- insert stuff in preamble
    "
}
handle_flag() {
    flag="$1"
    for flag in "$@"; do
        case "$flag" in
        --help|h)
            disp_help && exit 0
            ;;
        --debug|-d)
            debug=1
            ;;
        --preview|-p)
            preview=1
            ;;
        --inverse|-i)
            inverse=1
            ;;
        --no-math|-n)
            nomath=1
            ;;
        --tmath|-t)
            tmath=1
            ;;
        *)
            ;;
        esac
    done
}

if [[ -z "$1" ]]; then
    disp_help && exit 0
else
    for arg in "$@"; do
        if [[ "${arg:0:1}" = '-' ]]; then
            handle_flag $arg
        else
            formula="${formula}${arg}"
        fi
    done
fi

#more checks!
[[ -z "$formula" ]] && echo "Nothing to be TeX'ed" && exit 1

curdir=`pwd`
workdir="/tmp/easyltx_files"
[ -d "$workdir" ] || mkdir "$workdir" 
cd "$workdir"

[[ $debug == 0 ]] && output='&> /dev/null'
name=easytexput   #`date +"%Y%m%d_%H%M%S"`

[[ $inverse == 1 ]] && inversebeg='\pagecolor[rgb]{0.114, 0.122, 0.129}\color{white}' && inverseend=''
#[[ $inverse == 1 ]] && preamb=${preamb}'\pagecolor{black}\color{white}'

[[ $nomath == 1 ]] && begmath='' && endmath=''

if [[ $tmath  == 1 ]]; then 
    preamb="${preamb}
    \\usepackage{trmath}
    \\usepackage{trsym}
    " && export TEXINPUTS="~/opt/texfm/tex//:.::"
else
    preamb="${preamb}${mathpkg}"
fi

math="${begmath}${formula}${endmath}"
ltxcode="${preamb}${begin}${inversebeg}${math}${inverseend}${end}"

[[ $debug == 1  ]] && echo "$ltxcode"

retstat=0
# latex sometimes return 1 in almost valid cases
echo "$ltxcode"  | (eval latex -jobname=$name $output)
retstat=$?

(eval dvipng -T bbox -D 200 $name.dvi $output) && \
echo see "$workdir/${name}1.png" for output
retstat=$(($retstat + $?))
[[ $preview == 1 && $preview > 0 ]] && \
(eval xdg-open "$workdir/${name}1.png" $output &)

#mv texput1.png "$curdir"
cd "$curdir"
exit $retstat
























































