#!/bin/bash
preamb='
\relax
\documentclass[preview]{standalone}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[english,russian]{babel}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{xcolor}
\usepackage{nicefrac}
\newcommand\lfrac\nicefrac
'
begin='
\begin{document}
'
inversebeg=

begmath='
$\displaystyle
'
formula=

endmath='
$
'
inverseend=

end='
\end{document}
'
debug=0
preview=0
inverse=0
nomath=0
output=

disp_help() {
    echo "
    Usage: easyltx [flags...] '\sum_{i=1}^{\infty} a_i'
    Flags: 
        --debug,   -h --- print debug info
        --help,    -d --- display help
        --preview, -p --- preview generated image
        --inverse, -i --- inverse image colors
    "
}
handle_flag() {
    flag="$1"
    for flag in "$@"; do
        case "$flag" in
        --help)
            disp_help && exit 0
            ;;
        -h)
            disp_help && exit 0
            ;;
        -d)
            debug=1
            ;;
        --debug)
            debug=1
            ;;
        -p)
            preview=1
            ;;
        --preview)
            preview=1
            ;;
        -i)
            inverse=1
            ;;
        --inverse)
            inverse=1
            ;;
        -n)
            nomath=1
            ;;
        --no-math)
            nomath=1
            ;;
        *)
            ;;
        esac
    done
}

if [[ -z "$1" ]]; then
    disp_help && exit 0
else
    for arg in "$@"; do
        if [[ "${arg:0:1}" = '-' ]]; then
            handle_flag $arg
        else
            formula="${formula}${arg}"
        fi
    done
fi

#more checks!
[[ -z "$formula" ]] && echo "Nothing to be TeX'ed" && exit 1

curdir=`pwd`
workdir="/tmp/easyltx_files"
[ -d "$workdir" ] || mkdir "$workdir" 
cd "$workdir"

[[ $debug == 0 ]] && output='&> /dev/null'
name=easytexput   #`date +"%Y%m%d_%H%M%S"`

[[ $inverse == 1 ]] && inversebeg='\pagecolor[rgb]{0.114, 0.122, 0.129}\color{white}' && inverseend=''
#[[ $inverse == 1 ]] && preamb=${preamb}'\pagecolor{black}\color{white}'

[[ $nomath == 1 ]] && begmath='' && endmath=''

math="${begmath}${formula}${endmath}"
ltxcode="${preamb}${begin}${inversebeg}${math}${inverseend}${end}"

[[ $debug == 1  ]] && echo "$ltxcode"

echo "$ltxcode"  | (eval latex -jobname=$name $output) && \
    (eval dvipng -T bbox -D 200 $name.dvi $output) && \
    echo see "$workdir/${name}1.png" for output && [[ $preview == 1 ]] && \
    (eval xdg-open "$workdir/${name}1.png" $output &)
#mv texput1.png "$curdir"
cd "$curdir"
























































